import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import CustomQueryClient from "@/components/CustomQueryClient";

const poppins = Open_Sans({ subsets: ["latin"], weight: ["300", "400", "500"] });

export const metadata: Metadata = {
  title: "EV Analytics - Bet Like a Pro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <CustomQueryClient>
          <Navbar />
          {children}
          <Footer />
        </CustomQueryClient>
      </body>
    </html>
  );
}
